import pandas as pd
import random
from datetime import datetime, timedelta

class MockTwitterClient:
    def __init__(self):
        self.sample_tweets = [
            "I love Python programming! It's amazing for data science.",
            "Machine learning is transforming the world in incredible ways.",
            "AI technology is becoming more accessible every day.",
            "The future of artificial intelligence looks promising.",
            "Python libraries make data analysis so much easier.",
            "I'm frustrated with this code, it keeps giving errors.",
            "The documentation for this AI tool is terrible.",
            "Machine learning models can be so unpredictable sometimes.",
            "I hate when my training fails after hours of computation.",
            "This AI project is challenging but very interesting.",
            "Neutral tweet about technology and programming.",
            "Just reading about new developments in AI research.",
            "Python 3.11 has some nice performance improvements.",
            "Working on a sentiment analysis project today.",
            "I love Python programming! It's amazing for data science and machine learning.",
            "Machine learning is transforming the world in incredible ways. So exciting!",
            "AI technology is becoming more accessible every day. This is fantastic!",
            "The future of artificial intelligence looks very promising and bright.",
            "Python libraries make data analysis so much easier and efficient.",
            "This AI project is challenging but very interesting and rewarding.",
            "Neural networks are fascinating and powerful tools for prediction.",
            "Data science with Python is such a rewarding career choice.",
            "I'm really enjoying learning about deep learning algorithms.",
            "Natural language processing has made incredible progress recently.",
            "Python 3.11 has some nice performance improvements. Great work!",
            "The AI community is so supportive and collaborative. Love it!",
            "Just built my first machine learning model successfully! So happy!",
            "TensorFlow and PyTorch are amazing frameworks for deep learning.",
            "Computer vision applications are becoming incredibly accurate.",
            "Reinforcement learning is solving complex problems beautifully.",
            "The advancements in GPT models are truly remarkable.",
            "Data visualization with Plotly creates stunning charts easily.",
            "Jupyter notebooks make prototyping so convenient and fast.",
            "The scikit-learn library is incredibly well-designed and useful.",
            "Open source AI projects are changing the world for the better.",
            "I'm impressed by how fast AI research is progressing.",
            "Cloud computing makes AI deployment so much simpler.",
            "The Python ecosystem for AI is rich and well-maintained.",
            "Transfer learning saves so much time and computational resources.",
            "AI in healthcare is saving lives and improving diagnostics.",
            "The attention mechanism in transformers is brilliant.",
            "AutoML tools are making AI accessible to everyone.",
            "I love how AI can generate creative content and art.",
            "The AI ethics community is doing important work.",
            "Federated learning preserves privacy while enabling AI.",
            "Quantum machine learning is an exciting new frontier.",
            "AI for climate change solutions gives me hope.",
            "The democratization of AI technology is wonderful.",
            "I'm grateful for all the open source AI contributions.",
            "Python is a programming language used for data analysis.",
            "Machine learning is a subset of artificial intelligence.",
            "AI systems can process large amounts of data.",
            "Neural networks consist of layers of neurons.",
            "Data science involves statistics and programming.",
            "I'm reading about new developments in AI research.",
            "Python 3.11 was released with various improvements.",
            "Working on a sentiment analysis project today.",
            "The transformer architecture is used in NLP models.",
            "Computer vision deals with image recognition tasks.",
            "Reinforcement learning involves agents and environments.",
            "I attended a conference about machine learning applications.",
            "The paper discusses novel approaches to deep learning.",
            "Data preprocessing is an important step in ML pipelines.",
            "Feature engineering can improve model performance.",
            "Hyperparameter tuning optimizes algorithm settings.",
            "Cross-validation helps evaluate model generalization.",
            "The dataset contains various types of information.",
            "Model deployment requires careful consideration.",
            "API endpoints allow interaction with ML models.",
            "Cloud platforms provide scalable computing resources.",
            "Version control is important for collaborative projects.",
            "Documentation helps users understand code functionality.",
            "Testing ensures code reliability and correctness.",
            "Code reviews improve software quality and knowledge sharing.",
            "Agile methodologies organize development processes.",
            "Continuous integration automates testing and deployment.",
            "Containers package applications with dependencies.",
            "Microservices architecture enables scalable systems.",
            "Monitoring tracks system performance and health.",
            "I'm frustrated with this code, it keeps giving errors and won't run properly.",
            "The documentation for this AI tool is terrible and completely unhelpful.",
            "Machine learning models can be so unpredictable and difficult to debug sometimes.",
            "I hate when my training fails after hours of computation due to memory issues.",
            "This library has terrible performance and uses too much CPU resources.",
            "The API limits are too restrictive for meaningful development work.",
            "I'm struggling with overfitting in my neural network model.",
            "The dataset is too small for proper machine learning training.",
            "Feature engineering is taking forever and showing little improvement.",
            "Model deployment is much more complicated than I expected.",
            "The cloud costs for training large models are prohibitively expensive.",
            "I'm disappointed with the accuracy of my classification model.",
            "Debugging tensor shape errors in deep learning is frustrating.",
            "The pretrained model doesn't work well with my specific data.",
            "I'm having trouble reproducing results from research papers.",
            "The learning curve for this framework is too steep.",
            "My model keeps predicting the same class for all inputs.",
            "Data cleaning is taking much longer than anticipated.",
            "I'm frustrated with the lack of good tutorials for this topic.",
            "The community support for this library is practically nonexistent.",
            "Version compatibility issues are causing constant problems.",
            "The model performance degraded after the latest update.",
            "I'm overwhelmed by the number of hyperparameters to tune.",
            "The training process is too slow even with GPU acceleration.",
            "I'm concerned about bias in the training dataset.",
            "The model explanations don't make sense for my use case.",
            "I'm stuck on this problem and can't find solutions online.",
            "The academic paper is too theoretical for practical implementation.",
            "I'm frustrated with the poor quality of available datasets.",
            "The API changed without proper documentation or migration guide.",
            "My experiments are not showing any meaningful improvements.",
            "I'm worried about the environmental impact of large AI models.",
            "The model works well in testing but fails in production.",
            "I'm disappointed by the lack of innovation in this area.",
            "The tool is too complicated for simple tasks I need to accomplish.",
             "I love Python programming! 🐍 It's amazing for data science and machine learning. ❤️",
    "Machine learning is transforming the world in incredible ways! 🌍✨ So exciting! 😊",
    "AI technology is becoming more accessible every day. 🚀 This is fantastic! 👍",
    "The future of artificial intelligence looks very promising and bright. 🌟🤖",
    "Python libraries make data analysis so much easier and efficient! 📊🐼",
    "Just built my first machine learning model successfully! 🎉 So happy! 😄",
    "TensorFlow and PyTorch are amazing frameworks for deep learning! 🧠⚡",
    "Data visualization with Plotly creates stunning charts easily! 📈🎨",
    "Jupyter notebooks make prototyping so convenient and fast! ⚡📓",
    "Open source AI projects are changing the world for the better! 🌍❤️",
    "I'm impressed by how fast AI research is progressing! 🚀👏",
    "Cloud computing makes AI deployment so much simpler! ☁️⚡",
    "The Python ecosystem for AI is rich and well-maintained! 🐍💪",
    "AI in healthcare is saving lives and improving diagnostics! 🏥💊",
    "The attention mechanism in transformers is brilliant! 🤯🎯",
    "I love how AI can generate creative content and art! 🎨🤖",
    "Quantum machine learning is an exciting new frontier! ⚛️🚀",
    "AI for climate change solutions gives me hope! 🌱🌍",
    "The democratization of AI technology is wonderful! 👥❤️",
    "I'm grateful for all the open source AI contributions! 🙏💻",
    "Python is a programming language used for data analysis. 🐍📊",
    "Machine learning is a subset of artificial intelligence. 🤖🧠",
    "AI systems can process large amounts of data. 💾⚡",
    "Neural networks consist of layers of neurons. 🧠🔗",
    "Data science involves statistics and programming. 📈💻",
    "I'm reading about new developments in AI research. 📚🤔",
    "Python 3.11 was released with various improvements. 🐍🆕",
    "Working on a sentiment analysis project today. 📊🤖",
    "The transformer architecture is used in NLP models. 🔄📝",
    "Computer vision deals with image recognition tasks. 👁️🖼️",
    "Reinforcement learning involves agents and environments. 🎮🤖",
    "I attended a conference about machine learning applications. 🎤👥",
    "Data preprocessing is an important step in ML pipelines. ⚙️📊",
    "Feature engineering can improve model performance. 🔧📈",
    "Hyperparameter tuning optimizes algorithm settings. 🎛️⚡",
    "Cross-validation helps evaluate model generalization. ✅📊",
    "The dataset contains various types of information. 📁📊",
    "Model deployment requires careful consideration. 🚀🤔",
    "API endpoints allow interaction with ML models. 🔌🤖",
    "Version control is important for collaborative projects. 📝👥",
    "I'm frustrated with this code 😤, it keeps giving errors and won't run properly. 💥",
    "The documentation for this AI tool is terrible 😫 and completely unhelpful. 📚❌",
    "Machine learning models can be so unpredictable 😕 and difficult to debug sometimes. 🐛",
    "I hate when my training fails 😭 after hours of computation due to memory issues. 💾💥",
    "This library has terrible performance 🐢 and uses too much CPU resources. 🔥",
    "The API limits are too restrictive 🔒 for meaningful development work. 🚫",
    "I'm struggling with overfitting in my neural network model. 📈➡️📉",
    "The dataset is too small 📉 for proper machine learning training. 🤏",
    "Feature engineering is taking forever ⏳ and showing little improvement. 😓",
    "Model deployment is much more complicated 😰 than I expected. 🚀❌",
    "The cloud costs for training large models are prohibitively expensive. 💸☁️",
    "I'm disappointed 😞 with the accuracy of my classification model. 📊❌",
    "Debugging tensor shape errors in deep learning is frustrating. 🔢❌",
    "The pretrained model doesn't work well with my specific data. 🤖❌",
    "I'm having trouble reproducing results from research papers. 📄❌",
    "The learning curve for this framework is too steep. 📈😫",
    "My model keeps predicting the same class for all inputs. 🔄❌",
    "Data cleaning is taking much longer than anticipated. 🧹⏰",
    "I'm frustrated 😠 with the lack of good tutorials for this topic. 📚❌",
    "The community support for this library is practically nonexistent. 👥❌",
    "Just finished debugging my code! 🎉 It was a nightmare 😰 but now it works! ✅",
    "Training my AI model... 50% complete ⏳, hoping for good results! 🤞📊",
    "Spent 5 hours fixing one bug 🐛, but learned a lot! 🧠💡",
    "Git merge conflicts are the worst! 😫 But resolving them feels great! ✅",
    "Coffee ☕ + coding 💻 = productivity! But also bugs 🐛 sometimes...",
    "My code works on my machine 💻 but not in production 🚀... typical! 😅",
    "Learning new framework: excited 🎉, confused 🤔, frustrated 😤, enlightened 💡 - all in one day!",
    "Documentation says one thing 📖, code does another 💻... why?! 😫",
    "Fixed a bug that was causing 90% of the issues! 🐛➡️✅ Now time for coffee ☕",
    "AI predicted I'd be happy with these results... it was wrong 😞 but close! 🤖❌",
    "Coding at 2 AM 🌙: brilliant ideas 💡 or sleep deprivation? 🤷‍♂️",
    "Just realized I've been using the wrong algorithm for weeks 😱... time to start over 🔄",
    "My code is like a box of chocolates 🍫: you never know what you're gonna get!",
    "Trying to explain my bug to rubber duck 🦆... it's not helping! 😅",
    "Commit message: 'fixed stuff' 💾... I'll regret this tomorrow 😬",
    "When the code compiles on first try 🎊 vs when it doesn't after 10 tries 😭",
    "Refactoring: making it better ✨ or breaking everything 💥? Time will tell! ⏰",
    "My IDE suggestions are getting too smart 🤖... or am I getting dumber? 🤔",
    "Coding with music 🎧: productivity booster 🚀 or distraction 🎵?",
    "When you finally understand recursion: mind blown 🤯 but also headache 🤕"
        ]
    
    def collect_tweets(self, query, max_tweets=200):
        """Simule la collecte de tweets pour tester le pipeline"""
        try:
            tweets_data = []
            
            for i in range(min(max_tweets, len(self.sample_tweets))):
                tweet_data = {
                    'tweet_id': random.randint(100000, 999999),
                    'text': self.sample_tweets[i],
                    'created_at': datetime.now() - timedelta(hours=random.randint(1, 168)),
                    'user_name': f'user_{random.randint(1000, 9999)}',
                    'user_followers_count': random.randint(100, 10000),
                    'retweet_count': random.randint(0, 100),
                    'favorite_count': random.randint(0, 500),
                    'language': 'en'
                }
                tweets_data.append(tweet_data)
            
            print(f"🧪 {len(tweets_data)} tweets simulés collectés pour '{query}'")
            return pd.DataFrame(tweets_data)
            
        except Exception as e:
            print(f"❌ Erreur lors de la collecte simulée: {e}")
            return pd.DataFrame()